import React, { createContext, useContext, useState, useEffect } from 'react';

type Lang = 'ar' | 'en';

export const translations = {
  ar: {
    dashboard: 'يومياتي',
    history: 'السجل',
    settings: 'الإعدادات',
    logout: 'خروج',
    addFood: 'ضيف أكل',
    suggest: 'اقترحلي',
    today: 'النهاردة',
    trackSubtitle: 'تابع أكلك وظبط سعراتك.',
    caloriesRemaining: 'السعرات الباقية',
    protein: 'بروتين',
    carbs: 'كارب',
    fat: 'دهون',
    foodLog: 'أكل النهاردة',
    noFood: 'لسه مسجلتش أكل النهاردة.',
    addSomething: 'ضيف أكل عشان تتابع تقدمك!',
    addFoodTitle: 'سجل أكل بالذكاء الاصطناعي',
    quantity: 'الكمية',
    foodItem: 'الصنف',
    addAnother: 'ضيف صنف كمان',
    mealType: 'الوجبة',
    breakfast: 'فطار',
    lunch: 'غدا',
    dinner: 'عشا',
    snack: 'تلقيطة/سناك',
    time: 'الوقت',
    date: 'التاريخ',
    calculateAndAdd: 'احسب وضيف',
    calculating: 'بيحسب...',
    aiPowered: 'مدعوم بالذكاء الاصطناعي. بيستخدم أحدث بيانات 2026.',
    historyTitle: 'السجل',
    historySubtitle: 'راجع أكلك في الأيام اللي فاتت.',
    noRecords: 'مفيش سجلات',
    noRecordsDesc: 'مسجلتش أي أكل في اليوم ده.',
    settingsTitle: 'الإعدادات',
    settingsSubtitle: 'ظبط أهدافك اليومية.',
    dailyTargets: 'أهدافك اليومية',
    dailyCalorieGoal: 'الهدف اليومي للسعرات',
    proteinTarget: 'هدف البروتين',
    carbsTarget: 'هدف الكربوهيدرات',
    fatTarget: 'هدف الدهون',
    saveChanges: 'احفظ التغييرات',
    settingsSaved: 'تم حفظ الإعدادات بنجاح!',
    dailyCalories: 'السعرات اليومية (كالوري)',
    saveTargets: 'احفظ الأهداف',
    saving: 'بيحفظ...',
    saved: 'اتحفظ بنجاح!',
    loginTitle: 'أهلاً بيك تاني',
    createAccount: 'اعمل حساب جديد',
    email: 'البريد الإلكتروني',
    password: 'كلمة السر',
    rememberMe: 'افتكرني',
    signIn: 'دخول',
    signingIn: 'بيدخل...',
    registerTitle: 'اعمل حساب',
    haveAccount: 'عندك حساب؟',
    registering: 'بيسجل...',
    smartSuggestions: 'اقتراحات ذكية',
    analyzing: 'بيحلل الماكروز بتاعتك...',
    empty: 'فاضي',
    kcal: 'كالوري',
    g: 'جم',
    delete: 'مسح',
    language: 'English',
    mealTiming: 'توقيت الوجبة',
    edit: 'تعديل',
    recalculate: 'إعادة حساب',
    editFood: 'تعديل الأكل',
    foodNameAndQuantity: 'اسم الأكل والكمية',
    installApp: 'تثبيت التطبيق',
    installInstructions: 'لتثبيت التطبيق على الآيفون: اضغط على زر المشاركة (Share) تحت في المتصفح وبعدين اختار "إضافة للشاشة الرئيسية" (Add to Home Screen). على الأندرويد: من قائمة المتصفح (الثلاث نقط) اختار "تثبيت التطبيق" (Install App).',
    close: 'إغلاق',
    copyright: 'جميع الحقوق محفوظة © 2026 دكتور محي',
    welcomeDrMohie: 'أهلاً بيك في NutriTrack',
    appDescription: 'مع دكتور محي • تابع أكلك وسعراتك بذكاء وسهولة.',
    analytics: 'التحليل',
    analyticsTitle: 'التحليل والمتابعة',
    analyticsSubtitle: 'ملخص الأسبوع وتأثير الأكل على الأنسولين.',
    weeklySummary: 'ملخص الأسبوع',
    mealDistribution: 'توزيع الوجبات',
    drMohieInsights: 'نصائح دكتور محي ✨',
    analyzeWeekly: 'حلل الأسبوع وتوقيت الوجبات',
    insulinAnalysis: 'تحليل السكر وتوقيت الوجبات',
    weeklyTarget: 'الهدف الأسبوعي',
    consumedWeekly: 'المستهلك',
    remainingWeekly: 'المتبقي',
    proPlan: 'باقة دكتور محي VIP 👑',
    proPlanDesc: 'افتح تحليل الذكاء الاصطناعي الشامل والاقتراحات الذكية.',
    subscribeNow: 'اشترك بـ 499 ج.م / شهر',
    subscribing: 'جاري التحويل...',
    subscribeSuccess: 'تم الاشتراك بنجاح! مرحباً بك في باقة الـ VIP.',
    subscribeCanceled: 'تم إلغاء عملية الاشتراك.',
    lockedFeature: 'عذراً، هذه الميزة للمشتركين في باقة VIP.',
    unlockNow: 'افتح الميزات الآن',
    adminPanel: 'لوحة الإدارة',
    home: 'الرئيسية',
    pricing: 'الأسعار',
    terms: 'الشروط والأحكام',
    privacy: 'سياسة الخصوصية',
    landingHeroTitle: 'متابع الدايت الذكي مع د.محي',
    landingHeroSubtitle: 'سجل أكلك، تابع سعراتك، واحصل على تحليل ذكي 100% بالذكاء الاصطناعي عشان تتجنب ثبات الوزن ومقاومة الإنسولين.',
    getStarted: 'ابدأ رحلتك مجاناً',
    viewPricing: 'شاهد خطط الأسعار',
    basicPlan: 'الخطة الأساسية',
    advancedPlan: 'خطة الـ VIP 👑',
    free: 'مجاني',
    egpMo: 'جنيه / شهر',
    basicFeature1: 'تسجيل الوجبات والسعرات',
    basicFeature2: 'أهداف الماكروز الأساسية',
    basicFeature3: 'مراجعة السجل اليومي',
    vipFeature1: 'تحليل أسبوعي شامل للماكروز',
    vipFeature2: 'تتبع تأثير الأكل على الإنسولين',
    vipFeature3: 'ترشيحات ذكية لتعديل الدايت',
    vipFeature4: 'تواصل مخصص ونصائح دكتور محي',
    termsIntro: 'مرحباً بك في تطبيق NutriTrack. باستخدامك لهذا التطبيق، فإنك توافق على الشروط والأحكام التالية التي تضمن استخداماً آمناً وفعالاً للمنصة.',
    privacyIntro: 'نحن في NutriTrack نحترم خصوصيتك. يتم تشفير جميع البيانات الصحية وبيانات التغذية الخاص بك بأعلى معايير الأمان، ولا تتم مشاركة معلوماتك مع أي أطراف ثالثة.',
    subscribePaymob: 'اشترك الآن',
    refundPolicy: 'سياسة الاسترجاع والإلغاء',
    howItWorks: 'كيف تعمل الخدمة؟',
    step1Title: '1. سجل وجباتك',
    step1Desc: 'استخدم الأداة المجانية يومياً لتسجيل الأصناف التي تتناولها وحساب السعرات الحرارية بدقة.',
    step2Title: '2. اشترك في الـ VIP',
    step2Desc: 'اشترك في خطة الـ VIP المدفوعة لتفعيل المحرك الذكي وتحليل بياناتك وتاريخك الغذائي.',
    step3Title: '3. احصل على التحليل',
    step3Desc: 'يقوم الذكاء الاصطناعي بإصدار تقارير أسبوعية مفصلة وتوجيهات دقيقة لتحسين نمطك الغذائي.',
    firstName: 'الاسم الأول',
    lastName: 'الاسم الأخير',
    age: 'السن',
    height: 'الطول (سم)',
    weight: 'الوزن (كجم)',
    activityLevel: 'المجهود اليومي (طبيعة شغلك)',
    sedentary: 'مكتبي (قليل الحركة)',
    light: 'حركة خفيفة',
    moderate: 'مجهود متوسط',
    active: 'حركة نشطة',
    veryActive: 'مجهود شاق/رياضي',
    chronicDiseases: 'الأمراض المزمنة',
    chronicDesc: 'مثال: سكر، ضغط، غدة... (عشان السيستم يراعيها في التحليل)',
    optional: 'اختياري',
    profile: 'الصفحة الشخصية',
    editProfileDesc: 'تعديل بياناتك الطبية والشخصية.',
    saveProfile: 'حفظ البيانات',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    progress: 'تطور الجسم والتتبع',
    trackProgress: 'سجل قياساتك عشان تشوف الفرق في الحرق والمقاسات',
    addMeasurement: 'إضافة قياس جديد',
    bodyFat: 'نسبة الدهون (%)',
    waist: 'محيط الخصر/البطن (سم)',
    chest: 'محيط الصدر (سم)',
    hips: 'محيط الأرداف (سم)',
    arms: 'محيط الذراع (سم)',
    thighs: 'محيط الفخذ (سم)',
    aiAnalysis: 'تحليل ذكي للحالة والتطور',
    upgradeForAnalysis: 'التحليل الذكي واقتراحات الأعشاب والمكملات متاحة فقط في باقة الـ VIP.',
    generatingAnalysis: 'جاري تحليل القياسات والتطور...',
    normalRange: 'الطبيعي: ',
    measureHow: 'إزاي تقيس: ',
    measureWeightHow: 'أول حاجة الصبح، بعد الحمام، وقبل الأكل للحصول على أدق وزن.',
    measureBodyFatHow: 'باستخدام ميزان InBody أو ميزان دهون ذكي.',
    measureWaistHow: 'قيس بالمازورة من أضيق منطقة في الوسط (فوق السرة بشوية).',
    measureChestHow: 'قيس بالمازورة حوالين أعرض منطقة في الصدر بشكل مستوي.',
    measureHipsHow: 'قيس بالمازورة حوالين أعرض منطقة في الأرداف.',
    measureArmsHow: 'شد عضلة الباي وقيس من أعرض نقطة في الذراع.',
    measureThighsHow: 'قيس من أتخن نقطة في الفخذ وانت واقف متوازن.',
    noMeasurements: 'لسة مفيش قياسات، ابدأ دلوقتي ضيف قياساتك وتابع تطورك!',
    newMeasurement: 'تسجيل قياس جديد',
    saveMeasurement: 'حفظ القياس',
    tips: 'توصيات وأعشاب',
    manualEntry: 'إدخال يدوي',
    snapMeal: 'توقع بالكاميرا 📷',
    uploadOrTake: 'صور الطبق أو ارفع صورة 📸',
    analyzingImage: 'الذكاء الاصطناعي بيشوف الأكل...',
    imageAnalyzed: 'تم تحليل الصورة! راجع البيانات تحت',
    imageError: 'معرفتش أفهم الصورة. حاول تأخد صورة أوضح للوجبة.',
  },
  en: {
    dashboard: 'Dashboard',
    history: 'History',
    settings: 'Settings',
    logout: 'Logout',
    addFood: 'Add Food',
    suggest: 'Suggest',
    today: 'Today',
    trackSubtitle: 'Track your nutrition and stay on target.',
    caloriesRemaining: 'Calories Remaining',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    foodLog: 'Food Log',
    noFood: 'No food logged yet today.',
    addSomething: 'Add something to see your progress!',
    addFoodTitle: 'Add Food with AI',
    quantity: 'Quantity',
    foodItem: 'Food Item',
    addAnother: 'Add another item',
    mealType: 'Meal',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snack: 'Snack',
    time: 'Time',
    date: 'Date',
    calculateAndAdd: 'Calculate & Add',
    calculating: 'Calculating...',
    aiPowered: 'Powered by Gemini AI. Uses highly accurate 2026 nutritional data.',
    historyTitle: 'History',
    historySubtitle: 'Review your past nutrition logs.',
    noRecords: 'No records found',
    noRecordsDesc: 'You didn\'t log any food on this day.',
    settingsTitle: 'Settings',
    settingsSubtitle: 'Customize your daily nutrition goals.',
    dailyTargets: 'Daily Targets',
    dailyCalorieGoal: 'Daily Calorie Goal',
    proteinTarget: 'Protein Target',
    carbsTarget: 'Carbs Target',
    fatTarget: 'Fat Target',
    saveChanges: 'Save Changes',
    settingsSaved: 'Settings saved successfully!',
    dailyCalories: 'Daily Calories (kcal)',
    saveTargets: 'Save Targets',
    saving: 'Saving...',
    saved: 'Saved successfully!',
    loginTitle: 'Welcome back',
    createAccount: 'create a new account',
    email: 'Email address',
    password: 'Password',
    rememberMe: 'Remember me',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    registerTitle: 'Create an account',
    haveAccount: 'Already have an account?',
    registering: 'Creating account...',
    smartSuggestions: 'Smart Suggestions',
    analyzing: 'Analyzing your macros...',
    empty: 'Empty',
    kcal: 'kcal',
    g: 'g',
    delete: 'Delete',
    language: 'العربية',
    mealTiming: 'Meal Timing',
    edit: 'Edit',
    recalculate: 'Recalculate',
    editFood: 'Edit Food',
    foodNameAndQuantity: 'Food Name & Quantity',
    installApp: 'Install App',
    installInstructions: 'To install on iOS: Tap the Share button at the bottom of Safari, then select "Add to Home Screen". On Android/Desktop: Use the browser menu to select "Install App".',
    close: 'Close',
    copyright: 'All rights reserved © 2026 Dr. Mohie',
    welcomeDrMohie: 'Welcome to NutriTrack',
    appDescription: 'With Dr. Mohie • Track your food and calories smartly.',
    analytics: 'Analytics',
    analyticsTitle: 'Analytics & Tracking',
    analyticsSubtitle: 'Weekly summary and insulin impact analysis.',
    weeklySummary: 'Weekly Summary',
    mealDistribution: 'Meal Distribution',
    drMohieInsights: 'Dr. Mohie Insights ✨',
    analyzeWeekly: 'Analyze Week & Meal Timing',
    insulinAnalysis: 'Blood Sugar & Meal Timing Analysis',
    weeklyTarget: 'Weekly Target',
    consumedWeekly: 'Consumed',
    remainingWeekly: 'Remaining',
    proPlan: 'Dr. Mohie VIP Plan 👑',
    proPlanDesc: 'Unlock comprehensive AI analysis and smart suggestions.',
    subscribeNow: 'Subscribe for 499 EGP / mo',
    subscribing: 'Redirecting...',
    subscribeSuccess: 'Successfully subscribed! Welcome to the VIP plan.',
    subscribeCanceled: 'Subscription process was canceled.',
    lockedFeature: 'Sorry, this feature is for VIP subscribers.',
    unlockNow: 'Unlock Features Now',
    adminPanel: 'Admin Panel',
    home: 'Home',
    pricing: 'Pricing',
    terms: 'Terms & Conditions',
    privacy: 'Privacy Policy',
    landingHeroTitle: 'Smart Diet Tracker with Dr. Mohie',
    landingHeroSubtitle: 'Log your meals, track your macros, and get 100% AI-generated insights to avoid weight plateaus and insulin resistance.',
    getStarted: 'Start for Free',
    viewPricing: 'View Pricing',
    basicPlan: 'Basic Plan',
    advancedPlan: 'VIP Plan 👑',
    free: 'Free',
    egpMo: 'EGP / mo',
    basicFeature1: 'Log meals & calories',
    basicFeature2: 'Basic macro goals',
    basicFeature3: 'Daily history review',
    vipFeature1: 'Comprehensive weekly macro analysis',
    vipFeature2: 'Track insulin impact of meals',
    vipFeature3: 'Smart diet recommendations',
    vipFeature4: 'Personalized Dr. Mohie insights',
    termsIntro: 'Welcome to NutriTrack. By using this application, you agree to the following terms and conditions that ensure a safe and effective platform.',
    privacyIntro: 'At NutriTrack, we respect your privacy. All your health and nutrition data is encrypted with the highest security standards and never shared with third parties.',
    subscribePaymob: 'Subscribe Now',
    refundPolicy: 'Return & Refund Policy',
    howItWorks: 'How it Works',
    step1Title: '1. Log Meals',
    step1Desc: 'Use the free tool daily to record your food and calculate exact calories.',
    step2Title: '2. Subscribe to VIP',
    step2Desc: 'Upgrade to the paid VIP plan to unlock the AI engine and analysis.',
    step3Title: '3. Get Insights',
    step3Desc: 'Receive detailed weekly reports and actionable guidelines to improve your diet.',
    firstName: 'First Name',
    lastName: 'Last Name',
    age: 'Age',
    height: 'Height (cm)',
    weight: 'Weight (kg)',
    activityLevel: 'Activity Level',
    sedentary: 'Sedentary',
    light: 'Lightly Active',
    moderate: 'Moderately Active',
    active: 'Active',
    veryActive: 'Very Active',
    chronicDiseases: 'Chronic Diseases',
    chronicDesc: 'e.g. Diabetes, Hypertension... (for AI context)',
    optional: 'Optional',
    profile: 'Profile',
    editProfileDesc: 'Update your medical and personal data.',
    saveProfile: 'Save Profile',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    progress: 'Body Evolution',
    trackProgress: 'Track your body measurements and health evolution',
    addMeasurement: 'Add Measurement',
    bodyFat: 'Body Fat (%)',
    waist: 'Waist (cm)',
    chest: 'Chest/Bust (cm)',
    hips: 'Hips (cm)',
    arms: 'Arms (cm)',
    thighs: 'Thighs (cm)',
    aiAnalysis: 'AI Progress Analysis',
    upgradeForAnalysis: 'Upgrade to VIP for AI-powered health analysis, supplements, and tailored herb recommendations.',
    generatingAnalysis: 'Analyzing latest measurements...',
    normalRange: 'Normal Range: ',
    measureHow: 'How: ',
    measureWeightHow: 'Morning, after bathroom, empty stomach.',
    measureBodyFatHow: 'Use a smart scale or calipers.',
    measureWaistHow: 'Narrowest point of the torso.',
    measureChestHow: 'Widest part around bust/chest.',
    measureHipsHow: 'Widest part of buttocks.',
    measureArmsHow: 'Bicep peak, flexed.',
    measureThighsHow: 'Thickest part of the thigh.',
    noMeasurements: 'No measurements yet. Start tracking your body evolution!',
    newMeasurement: 'New Measurement',
    saveMeasurement: 'Save Record',
    tips: 'Tips & Herbs',
    manualEntry: 'Manual Entry',
    snapMeal: 'Snap Meal 📷',
    uploadOrTake: 'Take a photo or upload 📸',
    analyzingImage: 'AI is looking at your food...',
    imageAnalyzed: 'Image Analyzed! Review data below',
    imageError: 'Could not understand the image. Try a clearer photo.',
  }
};

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>('ar');

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const toggleLang = () => {
    setLang(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const t = (key: TranslationKey): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
